### DISCUSSION TITLE
Add Signoff Input

### DISCUSSION THREAD

**Discussion by xanjohns** [BetaHuhn/repo-file-sync-action#123] [Ideas] [answered]
It would be great if there were an input to the action that would add the "Signed-off by" line (--signoff) when making commits.

**Comment by BetaHuhn** [comment, marked as answer]
This should already be possible with the [`COMMIT_BODY`](https://github.com/BetaHuhn/repo-file-sync-action#custom-commit-body) input. It gets appended to each commit message (separated by two line returns).

In your case it would be:

```yml
- name: Run GitHub File Sync
  uses: BetaHuhn/repo-file-sync-action@v1
  with:
    GH_PAT: ${{ secrets.GH_PAT }}
    COMMIT_BODY: "Signed-off-by: Username"
```

The commit message will look like:

```
🔄 Synced local '<filename>' with remote '<filename>'

Signed-off-by: Username
```
