### DISCUSSION TITLE
Use message of original commit for sync commit

### DISCUSSION THREAD

**Discussion by BetaHuhn** [BetaHuhn/repo-file-sync-action#13] [Ideas] [answered]
Add an option to get the commit which changed the source file and use it's message instead of the default sync message for the commit in the target repo (It might be enough to just mention the commit that changed the file in the new commits message).

With this you get more context in the target repository on why a file was changed in the source, instead of the generic "file x was synced with y" message.

**Comment by cyberhck** [comment]
whoops, turns out we might also need a flag to turn on commit signing, we're not allowing unsigned commits :smile:

**Reply by cyberhck** [reply]
we can provide the private key I think to make this signature,

**Reply by BetaHuhn** [reply]
Check out the [ghaction-import-gpg](https://github.com/crazy-max/ghaction-import-gpg) Action. Haven't tested this, but if you run it before `repo-file-sync-action` it should sign all commits `repo-file-sync-action` makes.

**Reply by cyberhck** [reply]
hello @BetaHuhn any idea why that wouldn't work? I did the import gpg and auto sign all commits, that action succeeded, and then file sync ran, which did push, but the commit wasn't signed.

<details>
 <summary>Here's what I did:
</summary>

```
name: sync files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.MY_GPG }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Run file sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.MY_PAT }}
          BRANCH_PREFIX: sync_workflow_files
          COMMIT_PREFIX: "chore: "
          COMMIT_EACH_FILE: false
          GIT_EMAIL: "me@mydomain.com"
          GIT_USERNAME: "me"
```

</details>

<details>
 <summary>It did do a force push to the last PR, 
</summary>

```
Run crazy-max/ghaction-import-gpg@v3
📣 GnuPG info
🔮 Checking GPG private key
🔑 Importing GPG private key
🛒 Setting outputs...
🔐 Setting GPG signing keyID for this Git repository
🔨 Configuring Git committer (**censored** but valid)
💎 Sign all commits automatically
💎 Sign all pushes automatically

and then on file sync action:
Found existing PR 38
Locally syncing file(s) between source and target repository
Warning: Source others/.somefile (ignore this)
Pushing changes to target repository
Overwriting existing PR
Pull Request #38 created/updated: <pr>


Adding label(s) "sync" to PR
	
Cleanup complete
```

</details>
