### DISCUSSION TITLE
Sync entire repo

### DISCUSSION THREAD

**Discussion by ConstantinoSchillebeeckx** [BetaHuhn/repo-file-sync-action#130] [Q&A]
I'd like to use this to sync the entire contents of one repo to another, I've tried to configure the sync.yml like:
```yaml
owner/repo:
  - source: /
    deleteOrphaned: true
```
But am getting the errors:
```
Error: Cannot copy '/' to a subdirectory of itself, 'tmp-1636309511881/github.com/owner/repo@branch//'.
Error: Error: Cannot copy '/' to a subdirectory of itself, 'tmp-1636309511881/github.com/owner/repo@branch//'.
```

Is this possible or am I doing it wrong?
