### DISCUSSION TITLE
How to push directly to the target repositories

### DISCUSSION THREAD

**Discussion by N6REJ** [BetaHuhn/repo-file-sync-action#145] [Q&A]
I'm sorry to keep bothering you.. it's still saying there are syntax errors.  I must be blind.
![image](https://user-images.githubusercontent.com/1850089/146076448-2f24d5c2-ceae-4c77-a3ac-4737b735ec70.png)

I made the changes you told me too ( which phpstorm hates )
![image](https://user-images.githubusercontent.com/1850089/146076598-c04bf395-6ce5-4da7-923c-68a529a3ac02.png)

[Here's my repo'(https://github.com/Bearsampp/.settings)

**Comment by N6REJ** [comment]
fixed that error.. forgot to commit but then it said I can't use the secret name I used, so fixed that but then I get this..
![image](https://user-images.githubusercontent.com/1850089/146077552-cb4a83a0-335c-4d84-96db-7cf2447e5cfa.png)

**Reply by BetaHuhn** [reply]
Repos that contain special characters like a dot are not allowed as branch names, see https://github.com/BetaHuhn/repo-file-sync-action/issues/32. 

You need to manually specify a branch prefix.

This is not really your fault, I don't think the branch name limitation is documented well in the README

**Comment by N6REJ** [comment]
ok, tried a couple of things.. 
first I used 
![image](https://user-images.githubusercontent.com/1850089/146081314-95919f5a-6dc4-47f5-9c09-2afff55b2661.png)
but that doesn't really make any sense ( and the test proved it ) as it's the repo name that has the . not the branch.
![image](https://user-images.githubusercontent.com/1850089/146081284-ff0c1454-165d-4f9c-922f-62770e1d3262.png)

And, I added @main for website because it said it couldn't find "default" branch, which there isn't one named default ( I assume its look for the one assigned as default )

**Reply by BetaHuhn** [reply]
`SOURCE_REPO_NAME` will be replaced with the name of the source repository, so using it as the branch prefix doesn't go around the problem, the new branch will still have the dot from your repo's title in it.

You could change the `BRANCH_PREFIX` to a different string, like `repo-sync` and the resulting branch would be `repo-sync/default` for example.

You don't need to change the branch to main, the default is not the name of an existing branch, but a new one that will be created.

**Reply by N6REJ** [reply]
> `SOURCE_REPO_NAME` will be replaced with the name of the source repository, so using it as the branch prefix doesn't go around the problem, the new branch will still have the dot from your repo's title in it.
> 
> You could change the `BRANCH_PREFIX` to a different string, like `repo-sync` and the resulting branch would be `repo-sync/default` for example.
> 
> You don't need to change the branch to main, the default is not the name of an existing branch, but a new one that will be created.

so the bottom line is we can't have a repo with a "." name?

**Reply by BetaHuhn** [reply]
Again, yes you can.

By default it creates a new branch in the following format `repo-sync/SOURCE_REPO_NAME/SOURCE_BRANCH_NAME`, SOURCE_REPO_NAME will be replaced with the repositories name, in your case `.settings` and SOURCE_BRANCH_NAME with the name of the branch to action was triggered from, in your case the default branch (main).

After replacing the values the new branch would be `repo-sync/.settings/default` which throws an error because a branch can't have a dot in it. 

To prevent this, use the `BRANCH_PREFIX` option to change the text before SOURCE_BRANCH_NAME, so everything before `/default` in your case. Setting it to `sync` for example would change the new branch to `sync/default`.

All of that is not needed though if you want to push the changes directly to the target branch instead of creating a PR. When you enable this with the `SKIP_PR` option it won't create a new branch in the first place.

**Comment by N6REJ** [comment]
ok, imported to "config" repo and it now works completely EXCEPT it made a branch called https://github.com/Bearsampp/module-adminer/tree/config/default.  Really sorry @BetaHuhn to be a pest

**Reply by N6REJ** [reply]
What I want to happen is:
* I make a change to the global settings repo.
* It sends the change to all 40(ish) repos since they use the same files.
* Once it arrives at the repos its' automatically merged.

This way all the repos are kept using the same files.

**Reply by BetaHuhn** [reply]
Here's how you can achieve that:

`.github/workflows/sync.yml`:

```yml
name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: true
```

The `SKIP_PR` option as mentioned in the README skips the creation of a PR and directly pushes to the default branch (in your case main) of each specified target repository.

`sync.yml`:

```yml
group:
  - files:
      - source: .git-sync/site/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editor.config
        dest: .editor.config
      - source: img
        dest: img
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io
  - files: 
      - source: .git-sync/modules/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editor.config
        dest: .editor.config
      - source: img
        dest: img
    repos: |
      Bearsampp/module_apache
      Bearsampp/module_adminer
```

**Comment by N6REJ** [comment]
It's almost perfect now... 
I can't figure out where to put ```deleteOrphaned: true``` so that it removes any images ( or anything else ) that I delete.
for example, in https://github.com/Bearsampp/module-adminer/tree/master/img https://github.com/Bearsampp/module-adminer/blob/master/img/favicon-16x16.png should no longer exist.

**Reply by BetaHuhn** [reply]
Take a look at [this section](https://github.com/BetaHuhn/repo-file-sync-action#delete-orphaned-files) in the README.

You need to enable the option for each folder/directory you define with the `source` and `dest` keywords.

**Reply by N6REJ** [reply]
thats what I thought.. I'll try it again.

**Reply by N6REJ** [reply]
I have it right, and there are no errors, but its not purging the removed file.
```yml
group:
  - files:
      - source: .git-sync/site/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
        deleteOrphaned: true
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io

  - files:
      - source: .git-sync/modules/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editorconfig
        dest: .editorconfig
      - source: img
        dest: img
        deleteOrphaned: true
    repos: |
      Bearsampp/module-apache
      Bearsampp/module-adminer

```
https://github.com/Bearsampp/module-adminer/blob/master/img/favicon-16x16.png should no longer exist.

**Reply by BetaHuhn** [reply]
Hmm weird, your config looks right.

Could you try to enable [actions step debug mode](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging) by setting the repository secret `ACTIONS_STEP_DEBUG` to `true` and sharing the action run logs after rerunning your workflow?

**Comment by N6REJ** [comment]
sure.. and ty...
I hope this is the right one, never tried this before...
[logs_140.zip](https://github.com/BetaHuhn/repo-file-sync-action/files/7741708/logs_140.zip)

**Reply by BetaHuhn** [reply]
I might have found the problem and it could be a bug in the action.

Could you try to add a slash after the folder name? So `img` would become `img/`:

```yml
- source: img/
  dest: img/
  deleteOrphaned: true
```
