### DISCUSSION TITLE
Read PR Body from a local Markdown file

### DISCUSSION THREAD

**Discussion by CalvinRodo** [BetaHuhn/repo-file-sync-action#173] [Ideas] [answered]
I'm looking at using this in my org to enforce some standard workflows, I'd like to be able to provide a file for the PR Body as my PR message is going to be quite big and it's a little unruly to manage it the way it currently works.

**Comment by BetaHuhn** [comment, marked as answer]
There's a [file-reader](https://github.com/marketplace/actions/file-reader) action available which loads the contents of a file and provides them as a output variable which you can pass to this action.

Something like this should work (not tested):

```yml
- name: Read file contents
  id: read_file
  uses: andstor/file-reader-action@v1
  with:
    path: "pull_request_body.md"
- name: Run GitHub File Sync
  uses: BetaHuhn/repo-file-sync-action@v1
  with:
    GH_PAT: ${{ secrets.GH_PAT }}
    PR_BODY: ${{ steps.read_file.outputs.contents }}
```
