### DISCUSSION TITLE
Possibility to exclude a nested directory

### DISCUSSION THREAD

**Discussion by cazacutudor** [BetaHuhn/repo-file-sync-action#178] [Ideas]
## Description

Given the file structure,

```
- locals/
  - questions/
    - choices/
      - en.yml
      - fre.yml
    - responses/
      - en.yml
      - fre.yml
```

#### How it's currently working

Excluding functionality is working only when each file is specified individually,

.github/sync.yml
```yml
group:
  repos: |
    ionut/api
    dan/api
  files: 
    - source: locals/
      dest: system/locals/
      exclude: |
        en.yml
        responses/en.yml
        responses/fre.yml
      deleteOrphaned: true
```

#### Idea

What would be nice is to have the possibility to exclude the entire `responses/` directory, something like,

.github/sync.yml
```yml
group:
  repos: |
    ionut/api
    dan/api
  files: 
    - source: locals/
      dest: system/locals/
      exclude: |
        en.yml
        responses/
      deleteOrphaned: true
```

Thank you!
