### DISCUSSION TITLE
Is it possible to only sync on a push to the default branch?

### DISCUSSION THREAD

**Discussion by boudewijn-zicht** [BetaHuhn/repo-file-sync-action#225] [Ideas] [answered]
In our workflow we use release branches, so we can work concurrently in branches `release/1.0.x` and `release/1.1.x`.  However, I only want to run the sync workflow when _default_ branch is pushed.

So when `release/1.1.x` is the default branch a push to the `release/1.0.x` should not start the sync workflow.

From what I found it is not possible from github itself, but perhaps this can be tested within the repo-file-sync-action itself?

```yaml
name: Sync interproject files

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.REPO_SYNC_PERSONAL_ACCESS_TOKEN }}
          ASSIGNEES: boudewijn-zicht
```

**Comment by BetaHuhn** [comment, marked as answer]
During the action execution you have access to the default branch under `github.event.repository.default_branch`. You could add a check so the sync job only gets executed if the ref matches that value:

```yml
name: Sync interproject files

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  sync:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.REPO_SYNC_PERSONAL_ACCESS_TOKEN }}
          ASSIGNEES: boudewijn-zicht
```

See related [StackOverflow thread](https://stackoverflow.com/a/72080588).

Hope this helps!
