### DISCUSSION TITLE
Sync files based on repo regex to allow syncing across whole org.

### DISCUSSION THREAD

**Discussion by thomascrowley** [BetaHuhn/repo-file-sync-action#238] [Ideas] [answered]
Hi, it would be helpful if it was possible to sync to all repos in an org based on a regex.

For example, I have lots of Terraform modules and they all require the same workflows, so it would be great if you could use a  wildcard in the sync.yml.

for example, the implementation would look something like this: 

```
group:
  # first group
   - files:
       - source: workflows/build.yml
         dest: .github/workflows/build.yml
       - source: LICENSE.md
         dest: LICENSE
     repos: |
       my-super-secret-org/terraform-*
       user/something-else
```
