### DISCUSSION TITLE
allow deletion of specific files

### DISCUSSION THREAD

**Discussion by DarkAtra** [BetaHuhn/repo-file-sync-action#267] [Ideas]
We'd like to enforce that a specific file does not exist in all of our projects. It would be great if something like this would be possible:

```
group:
  - repos: ....
    files:
      - dest: .github/renovate.json
        delete: true
```

The above config could be an example on how to delete the `.github/renovate.json` file in each repo.
