### DISCUSSION TITLE
Using this action with github-app-token action

### DISCUSSION THREAD

**Discussion by Khaaz** [BetaHuhn/repo-file-sync-action#283] [Q&A]
As specified in the documentation, it is said that one can use [this action](https://github.com/tibdex/github-app-token) in order to commit and open PRs with a Github app.

After some trouble I managed to make it work and it seems to be using the token if I pass it as a env variable first.
See the code below:

```yaml
name: Sync
# https://github.com/marketplace/actions/repo-file-sync-action
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate GH token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PKEY }}
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.generate_token.outputs.token }}
          COMMIT_PREFIX: "sync: "
          PR_LABELS: |
            type: sync
            meta: automerge
            meta: automated
```

I have added the github app `app_id` as `GH_APP_ID` in the repository action secrets, and I have generated a private key in my app. I have added the key in its entirety (including the BEGIN RSA and END RSA) as `GH_APP_KEY` also in the repository action secrets.

My issue now is that when the action runs in the remote repository, I get the following error:
`Error: Bad credentials`

What am I doing wrong?
