### DISCUSSION TITLE
Ability to sync sub-folder to top-level destintation

### DISCUSSION THREAD

**Discussion by dalebradman** [BetaHuhn/repo-file-sync-action#296] [Ideas] [answered]
This might already be possible and I'm just missing the correct syntax but it would be great to be able to sync an entire sub-folder to the top-level folder of the destination.

Example:
```
files:
    - source: sub-folder-with-files/
      dest: /
```

This fails with the error `Error: Command failed: git add -f "/"` but is there a way to achieve this? We're currently having to explicitly set each file e.g.:

```
files:
    - source: sub-folder-with-files/file1
      dest: file1
    - source: sub-folder-with-files/file2
      dest: /file2
    - source: sub-folder-with-files/file3
      dest: /file3
```

Thanks!

**Comment by tbutler-qontigo** [comment, marked as answer]
Change your destination to `./` instead of `/` and it should work - I do this in one of my use cases:
```yaml
group:
  - files:
      - source: python/
        dest: ./
    repos: SomeRepo
```
