### DISCUSSION TITLE
Support string replace at sync configuration

### DISCUSSION THREAD

**Discussion by zzjin** [BetaHuhn/repo-file-sync-action#299] [Ideas]
If there would have feature like replace content when sync.

For example:
base repo have one readme file:
A-repo/README.md
``` 
![](./CONTRIBUTING.md)
```
and with synced to B repo, but under a sub direct using config yaml like this:
```yaml
B/repo:
  - source: README.md
    dest: repoA/docs/README.md
```
We need to change content inside readme.md `./CONTRIBUTING.md` => `../../CONTRIBUTING.md` (witch refers to B repo's CONTRIBUTING guide.

At this situation, we cannot use `templates` because A-repo's README file is its repos main file, and github do not support any templates with md file.

So we want some content replacement feature, to support add relative paths and/or change image link from relative to absolute (CDN) url:
```yaml
B/repo:
  - source: README.md
    dest: repoA/docs/README.md
    replace:
    - src: ./CONTRIBUTING.md
      dest: ../../CONTRIBUTING.md
    - src: ./img/intro.png
      dest: https://cdn.repoa.com/img/intro.png
```
