### DISCUSSION TITLE
Exclude wildcard pattern

### DISCUSSION THREAD

**Discussion by mihaigalos** [BetaHuhn/repo-file-sync-action#302] [Ideas]
Hi,

How can I exclude a wildcard pattern? This doesn't work:

```yaml
- source: client/workflows/
      dest: .github/workflows/
      template: false
      exclude: |
        secrets-sync.yaml
        *.template
```
