### DISCUSSION TITLE
GitHub fine-grained PAT

### DISCUSSION THREAD

**Discussion by Kwill3** [BetaHuhn/repo-file-sync-action#304] [Q&A] [answered]
There were concerns on the usage of the classic Personal Access Tokens but now with the launch of the fine-grained PAT, would it work the same way by using the secret?

**Comment by caleblloyd** [comment, marked as answer]
I am using a Fined Grained PAT with these options.  I noticed that the auto-detection of email based on the PAT did not work for the Fine Grained PATs so I had to explicitly set `GIT_USERNAME` and `GIT_EMAIL`

```
      with:
        GH_PAT: ${{ secrets.FINE_GRAINED_PAT }}
        IS_FINE_GRAINED: true
        GIT_USERNAME: your-git-username
        GIT_EMAIL: your-git-email
```

For the actual PAT, I am using these settings for the target repository:
- `Contents`: Read and Write
- `Pull requests`: Read and write
- `Metadata`: Read only (mandatory when checking Pull request)
