### DISCUSSION TITLE
Allow same repository with different branches

### DISCUSSION THREAD

**Discussion by bytestream** [BetaHuhn/repo-file-sync-action#51] [Ideas] [answered]
Hi,

Thanks for your efforts on this action.

I would like to keep multiple branches within the same repository up to date. For example, a repository named `foo/bar` with branch `main`, and `sync.yml` contents:
```yml
group:
  repos: |
    foo/bar@de
    foo/bar@es
    foo/bar@fr
  files:
    - source: .github/workflows/
      dest: .github/workflows/
```

It's not currently clear from the documentation but I tested and it currently only creates a PR for the first entry in the `repos` list.

I believe the limitation is in https://github.com/BetaHuhn/repo-file-sync-action/blob/7ca74d975aeecb6fba445255a0dad555a41c4b7b/src/config.js#L154 & https://github.com/BetaHuhn/repo-file-sync-action/blob/7ca74d975aeecb6fba445255a0dad555a41c4b7b/src/git.js#L57

Is this something you would be willing to support?
