### DISCUSSION TITLE
Leave out some files for specific entries in some groups

### DISCUSSION THREAD

**Discussion by icopp** [BetaHuhn/repo-file-sync-action#64] [Ideas]
For an example of what I mean, let's say I have these:

```
group:
  repos: |
      org-name/eslint-config-org-name
      org-name/jest-preset-org-name
      org-name/repo-for-actual-code
    files:
      - .editorconfig
      - .eslintrc
      - .gitignore
      - .npmrc
      - .yarnrc
      - jest.config.js
```

...except, I don't actually want to copy the `.eslintrc` or `jest.config.js` files to the `eslint-config-org-name` or `jest-preset-org-name` repo respectively, because neither tool can handle a recursive reference in a config file (`"extends": "@org-name/eslint-config-org-name"` inside that package itself will just result in a `not found`).

The syntax could potentially look like:

```
group:
  repos: |
    org-name/eslint-config-org-name
    org-name/jest-preset-org-name
    org-name/repo-for-actual-code
  files:
    - .editorconfig
    - source: .eslintrc
      dest: .eslintrc
      except: |
        org-name/eslint-config-org-name
    - .gitignore
    - .npmrc
    - .yarnrc
    - source: jest.config.js
      dest: jest.config.js
      except: |
        org-name/jest-preset-org-name
```

This would simplify the logic around working with any really long lists of files and repos.
