### ISSUE TITLE
Fails to sync

### ISSUE THREAD

**Issue by N6REJ** [BetaHuhn/repo-file-sync-action#144]
Having a problem where its not wanting to sync.

**🐞 Describe the bug**

Action will not process

**📚 To Reproduce**
run my file-sync.yml action

**💡 Expected behavior**

completes assigned tasks

**🖼️ Screenshots**

[[](http:// .github/workflows/file-sync.yml](https://github.com/Bearsampp/.settings/actions/runs/1576116884/workflow)

**Comment by BetaHuhn** [comment]
As you can see by the error `You have an error in your yaml syntax on line 10`, your [sync,yml](https://github.com/Bearsampp/.settings/blob/main/.github/sync.yml) is not valid and has an error at line 10:

https://github.com/Bearsampp/.settings/blob/b89963070c10353f65986978fbf2216aec4a2ef9/.github/sync.yml#L10-L15

You need to have a dash before every source file declaration as shown in the [README](https://github.com/BetaHuhn/repo-file-sync-action#sync-the-same-files-to-multiple-repositories), your configuration should look like this:

```yml
group:
  -
  # Test tebsite
  - files:
      - source: .git-sync/site/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editor.config
        dest: .editor.config
      - source: img
        dest: img
    repos: |
      Bearsampp/website
      Bearsampp/Bearsampp.github.io
  # second group - Normal modules
  - files:
      - source: .git-sync/modules/.github
        dest: .github
      - source: LICENSE
        dest: LICENSE
      - source: .gitignore
        dest: .gitignore
      - source: .editor.config
        dest: .editor.config
      - source: img
        dest: img
    repos: |
      Bearsampp/module_apache
      Bearsampp/module_adminer
```

Closing this as it is not a bug. Feel free to ask a question if something is not clear.
