### ISSUE TITLE
Template rendering doesn't work alongside `dest`

### ISSUE THREAD

**Issue by dalebradman** [BetaHuhn/repo-file-sync-action#297]
### 🐞 Describe the bug

It seems as though when you want to use the Jinja templating, you cannot specify the `dest` keyword in the config alongside `template`

### 📚 To reproduce

Set the `sync.yml` file to:
```
project/repo_1:
  - source: folder/file.py
    dest: file.py
    template:
      name: dale
```

Then the `file.py` file will incorrectly be rendered as:
```
name = {{ name }}
```

### 💡 Expected behavior

I'd like to set the `sync.yml` file as:
```
project/repo_1:
  - source: folder/file.py
    dest: another_folder/file.py
    template:
      name: dale
```

Which will be rendered as:
```
name = dale
```

### ⚙️ Environment

v1

**Comment by dalebradman** [comment]
Actually, I'm not 100% sure if the Python file is related to the issue. It might be more of a case that it doesn't work well with multiple sources:

```
project/repo_1:
  - source: folder/file_1.yml
    dest: another_folder/file_1.yml
    template:
      name: dale
  - source: folder/file_2.yml
    template:
      name: dale
```

`file_2.yml` renders and syncs correctly but `file_1.yml` does not.
