### ISSUE TITLE
sporadic "Server Error" on adding labels

### ISSUE THREAD

**Issue by kwavnet** [BetaHuhn/repo-file-sync-action#306]
### 🐞 Describe the bug

We have sporadic "Server Error" messages (and therefore failed pipelines) when the action is trying to set labels.
The label does exist in the downstream repo.
It's also not a permission issue, as we tried different levels of access tokens, all with the same result.

We are syncing a fairly large sync list (currently ~100 repositories)

Personal hunch: Could it be that we are hitting GitHub API rate limiting?

### 📚 To reproduce

```
- name: Run GitHub File Sync
  uses: BetaHuhn/repo-file-sync-action@v1.21.0
  with:
    GH_PAT: ${{ secrets.PAT }}
    COMMIT_EACH_FILE: false
    PR_LABELS: |
      sync
    COMMIT_PREFIX: "sync: "
    ORIGINAL_MESSAGE: true
```

- run this like 100 times with a change set, so a PR will be created/updated
- (doesn't matter a if a downstream PR already exists or not)
- (we tested it so far only with private repositories)

### 💡 Expected behavior

No "Server Error" or at least a more meaningful debug message

### ⚙️ Environment

- ubuntu-latest runner
- latest release of the action (1.21.0 by the time of writing)

### 📋 Additional context

log output

```
Repository Info
Slug		: my-private-repo
Owner		: my-org
Https Url	: https://github.com/my-org/my-private-repo
Branch		: main
	
Found existing PR 392
Locally syncing file(s) between source and target repository
Source is directory
Pushing changes to target repository
Overwriting existing PR
Notice: Pull Request #392 created/updated: https://github.com/my-org/my-private-repo/pull/392
Adding label(s) "sync" to PR
Error: Server Error
```
