### ISSUE TITLE
Exclude overlap causing missed files in sync

### ISSUE THREAD

**Issue by korverdev** [BetaHuhn/repo-file-sync-action#318]
### 🐞 Describe the bug

Using `exclude` in the sync config appears to break further overlapping sync group configs.

### 📚 To reproduce

Here's an abbreviated example:
```yaml
groups:
  - files:
      - folder/
        exclude: b.txt
    repos: |
      org/repo@master

  - files:
      - folder/b.txt
    repos: |
      org/repo@master
```

In this example, `b.txt` is never synced. In our use-case, we were looking to sync a mostly standard template that was structured appropriately, but include unique Dockerfiles from a different folder.

### 💡 Expected behavior

I'd expect both files `a.txt` and `b.txt` to be synced to the repo.

### ⚙️ Environment

v1.21.0
