### ISSUE TITLE
Sync subfolder to destination

### ISSUE THREAD

**Issue by mihaigalos** [BetaHuhn/repo-file-sync-action#322]
### 🐞 Describe the bug

I would like to sync a subfolder from the `direct_sync_to_root_of_repo` to the destination `.github` folder:
```
.
└── direct_sync_to_root_of_repo
    └── .github
        └── metaconfig.yaml
``` 

This however creates a PR under `direct_sync_to_root_of_repo/.github/metaconfig.yaml`.

### 📚 To reproduce

```yaml
group:
  - files:
    - source: direct_sync_to_root_of_repo/
      dest: ./
      template: false
```

### 💡 Expected behavior

Exact folder hierarchy syned to destination.

### ⚙️ Environment

v1.21.0
