### ISSUE TITLE
Exclude is not workin in the v1.21.1

### ISSUE THREAD

**Issue by juergenbosch** [BetaHuhn/repo-file-sync-action#346]
### 🐞 Describe the bug

I think the latest v1 release version is used if i defined: 
uses: BetaHuhn/repo-file-sync-action@v1

In the sync.yaml i have defined this:
```
SAP-ProductCompliance/API_Testing_TEMPLATE_REPO:
  - source: karate/
    template:
      config:
        name: '<REPLACE_WITH_REPO_NAME>'
        description: '<REPLACE_WITH_REPO_DESCRIPTION>'
        apiBaseUrl: '<REPLACE_WITH_API_BASE_URL>'
        jenkinsViewName: '<REPLACE_WITH_JENKINS_VIEW_NAME>'
        apiHubNameCE: '<REPLACE_WITH_CE_API_HUB_NAME>'
        apiHubNameOP: '<REPLACE_WITH_OP_API_HUB_NAME>'
    dest: ./
    exclude: |
      Jenkinsfile
  - source: karate/Jenkinsfile
    dest: _Jenkinsfile
```

And the source files structure is:
<img width="204" alt="image" src="https://github.com/user-attachments/assets/c9bfa5ed-665c-4fbd-afd9-647b2c70cf89">

The current outcome of the pull request in the target app looks like this:
<img width="332" alt="image" src="https://github.com/user-attachments/assets/099ed1c3-9d03-47e5-9cb6-587224c35e5c">

### 📚 To reproduce

-

### 💡 Expected behavior

The "Jenkinsfile" should be in the target pull request as "_Jenkinsfile".

### ⚙️ Environment

v1.21.1
