### ISSUE TITLE
Commits not verified

### ISSUE THREAD

**Issue by michalbachowski** [BetaHuhn/repo-file-sync-action#354]
### 🐞 Describe the bug

Commits made with installation token are not marked as verified.

### 📚 To reproduce

Calling action as follows:

```yaml
      - env:
          GITHUB_API_URL: ${{ github.server_url }}/api/v3
        id: sync-files
        name: Synchronise files
        with:
          BRANCH_PREFIX: feature/sync-files
          COMMIT_EACH_FILE: false
          COMMIT_PREFIX: "NOSTORY 🔄"
          CONFIG_PATH: ${{ env.SYNC_FILE_PATH }}
          GH_INSTALLATION_TOKEN: ${{ steps.gh-auth.outputs.token }}
          PR_LABELS: |
            automerge
            bot
            files-sync
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619
```

`${{ env.SYNC_FILE_PATH }}` is:

```yaml
group:
  - repos: |
      https://<gh-enterprise-hostname>/<org>/<repo>
    files:
      - a-file
```

### 💡 Expected behavior

Commits are marked as verified.

### 🖼️ Screenshots

<img width="920" alt="Image" src="https://github.com/user-attachments/assets/7e0a1cae-3de1-45fd-b1ed-09b9977b2b46" />

### ⚙️ Environment

action version: `8b92be3375cf1d1b0cd579af488a9255572e4619`
GitHub Enterprise.
